export default [
    {
        "uid": "Deadpool & Wolverine",
        "Hero": "Iron Man",
        "id": "Deadpool",
        "title": "Deadpool & Wolverine",
        "description": "Deadpole is a sarcastic, irreverent anti-hero with a regenerative ability, donning a red and black suit. He's a master of combat and wisecracks, often breaking the fourth wall. Wulvren, on the other hand, embodies primal ferocity and cunning. With enhanced senses and agility, he navigates the shadows in a sleek, wolf-like form. Together, they form an unlikely duo, blending Deadpole's humor and Wulvren's intensity in their quests, showcasing a balance of chaos and control in their dynamic partnership.",
        "year": 2024,
        "dlink": "",
        "rating": "",
        "himg":"https://w0.peakpx.com/wallpaper/11/61/HD-wallpaper-actors-robert-downey-jr-actor-american-sunglasses.jpg",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZDMwZjliMTUtOGRiNS00OTg1LTkyMDYtZjJmNmUxOWYzN2ViXkEyXkFqcGdeQXVyMTU5OTc2NTk@._V1_FMjpg_UX1025_.jpg",
        "images": [
            "https://w0.peakpx.com/wallpaper/179/730/HD-wallpaper-iron-man-mark-45-iron-man.jpg",
        ]
    },
    {
        "uid": "The Marvels",
        "Hero": "Captain America",
        "title": "The Marvels",
        "dlink": "https://pixeldrain.net/api/file/fpuXL2Ed?download",
        "description": "The Marvels is a 2023 American superhero film based on Marvel Comics. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the sequel to the film Captain Marvel (2019), a continuation of the television miniseries Ms. Marvel (2022), and the 33rd film in the Marvel Cinematic Universe (MCU). The film was directed by Nia DaCosta, who co-wrote the screenplay with Megan McDonnell and Elissa Karasik. It stars Brie Larson as Carol Danvers / Captain Marvel, Teyonah Parris as Monica Rambeau, and Iman Vellani as Kamala Khan / Ms. Marvel, alongside Zawe Ashton, Gary Lewis, Park Seo-joon, Zenobia Shroff, Mohan Kapur, Saagar Shaikh, and Samuel L. Jackson. In the film, Danvers, Rambeau, and Kamala team up as the Marvels after they begin swapping places with each other every time they use their powers.",
        "year": 2023,
        "discountPercentage": 15.6,
        "rating": 5.5,
        "stock": 114,
        "brand": "Al Munakh",
        "category": "fragrances",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BM2U2YWU5NWMtOGI2Ni00MGMwLWFkNjItMjgyZWMxNjllNTMzXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_FMjpg_UY2500_.jpg",
        "himg":"https://i.pinimg.com/564x/aa/3c/df/aa3cdfee58197bd079476f1b03a072e9.jpg",
        "images": [
            "https://w0.peakpx.com/wallpaper/724/29/HD-wallpaper-captain-america-captain-america-super-hero.jpg"
        ]
    },
    {
        "uid": "Ant-Man:Quantumania",
        "id": "Ant-Man",
        "Hero": "Spider-Man",
        "title": "Ant-Man and the Wasp:Quantumania",
        "description": "Ant-Man and the Wasp: Quantumania delves deeper into the quantum realm as Scott Lang (Ant-Man) and Hope van Dyne (The Wasp) navigate a new adventure fraught with unexpected challenges. As they grapple with family dynamics and personal struggles, they encounter Kang the Conqueror, a powerful and enigmatic villain with the ability to manipulate time. With stakes higher than ever, the duo teams up with allies old and new, embarking on a mind-bending journey through space and time to thwart Kang's nefarious plans and save the universe from impending doom.",
        "year": 2023,
        "discountPercentage": 15.6,
        "rating": 6.1,
        "stock": 114,
        "brand": "Al Munakh",
        "category": "fragrances",
        "himg":"https://www.pinkvilla.com/images/2022-09/tom_holland_15.jpg",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMDIzM2FlNTctNjAzZi00YzhkLThjYWQtMDY5Njc0NjdmMGVlXkEyXkFqcGdeQXVyMTUzOTcyODA5._V1_FMjpg_UX520_.jpg",
        "images": [
            "https://w0.peakpx.com/wallpaper/115/81/HD-wallpaper-amazing-spider-man-2-amazing-spider-man-amazing-spider-man-2-marvel-sony-spider-man.jpg",
        ]
    },
    {
        "uid": "Guardians of the Galaxy Vol.3",
        "title": "Guardians of the Galaxy Vol.3",
        "description": "In Guardians of the Galaxy Vol. 3 the ragtag team of misfits embarks on a galaxy-spanning odyssey filled with humor, heart, and high-stakes action. As they face their greatest challenge yet, the Guardians grapple with their pasts, forging deeper bonds of friendship and family amidst the chaos. With new allies and formidable foes entering the fray, the Guardians must confront their inner demons and unite against a cosmic threat that jeopardizes the very fabric of reality. Packed with interstellar adventures and emotional resonance, Vol. 3 promises to be an epic conclusion to the beloved trilogy.",
        "year": 2023,
        "rating": 7.9,
        "Hero": "Thor",
        "stock": 114,
        "thumbnail":"https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aa454069-1f38-4db1-a9e3-75d6b00c42e8/dfx419e-e0adccbd-8451-41dc-8540-bc37986b91c0.jpg/v1/fill/w_748,h_1069,q_70,strp/guardians_of_the_galaxy_vol_3_action_poster_by_akithefull_dfx419e-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTgyOSIsInBhdGgiOiJcL2ZcL2FhNDU0MDY5LTFmMzgtNGRiMS1hOWUzLTc1ZDZiMDBjNDJlOFwvZGZ4NDE5ZS1lMGFkY2NiZC04NDUxLTQxZGMtODU0MC1iYzM3OTg2YjkxYzAuanBnIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.OAxcpbR9VIc9vaVqZrh79U2ggNW8WjPOP38XxNlAoZg",
        "himg":"https://ca-times.brightspotcdn.com/dims4/default/812c7f8/2147483647/strip/true/crop/5076x3807+0+0/resize/1200x900!/format/webp/quality/75/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F8d%2Fe9%2Fde9f3fac4f3a85d28508df65e0e6%2Fny-premiere-of-limitless-with-chris-hemsworth-68062.jpg",
        "images": [
            "https://i.pinimg.com/originals/c1/56/2c/c1562cb765f280bb67044031295b1a76.jpg",
        ]
    },
    {
        "uid": "Doctor Strange",
        "id": "Doctor Strange Multiverse",
        "title": "Doctor Strange in the Multiverse of Madness",
        "popular": "popular",
        "year": 2022,
        "rating": 6.4,
        "Hero": "Hulk",
        "himg":"https://www.esquireme.com/cloud/2021/09/08/Mark-Ruffalo.jpg",
        "images": [
            "https://i.pinimg.com/originals/e7/83/d7/e783d72231e782f78fd0a280880a0540.jpg",
        ],
        "description": "Doctor Strange in the Multiverse of Madness delves into the mystical realms as Stephen Strange navigates a treacherous journey through alternate dimensions and parallel universes. Wrestling with the consequences of tampering with time, Strange confronts dark forces that threaten to unravel reality itself. Joined by allies old and new, including the enigmatic Scarlet Witch, he must harness his mastery of the mystic arts to combat ancient evils and restore balance to the multiverse. With mind-bending visuals and thrilling sorcery, the film promises to be a kaleidoscopic adventure that explores the boundless possibilities of the Marvel Cinematic Universe.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_FMjpg_UY2500_.jpg",
    },
    {
        "id": "Thor",
        "Hero": "Black Widow",
        "uid": "Thor: Love and Thunder",
        "title": "Thor: Love and Thunder",
        "year": 2022,
        "rating": 6.2,
        "himg":"https://networthxi.com/wp-content/uploads/2017/05/Scarlett-Johansson-Net-Worth-Age-Height-Husband-Profile-Movies-a.jpg",
        "images": [
            "https://i.pinimg.com/564x/23/32/7c/23327ca543110ffae03159d9dea91bd4.jpg",
        ],
        "dlink": "https://long-hall-4bd6.yahadat8701444.workers.dev/1396595190/94f664a8bd1e40359ab08354a1209bef43af08c0d82028a76419b5b568966df680ba54363d552f161b2c1df4ed42a758063f2df73192ad8dda2287be743a5c22241f444fdde12cc2b1858531356cb1ae2c2c787737a22f61bcd464b6db0aa18efd5d3f3bcdbbb408aa86b340915414ea35be2ba52bac0bc8ec922ccdf1409ba24a6e358d16a44f5eba307340ca5496c8314b103fb0235cfa55304d7c6b1fa639::ea9c0e2634abb08cd7246846aa6a593a/Thor.Love.and.Thunder.2022.BluRay.720p.Hindi.English.AAC.5.1.x264.MSubs.-.Vegamovies.to.mkv",
        "description": "In Thor: Love and Thunder, the God of Thunder returns with a thunderous roar, embarking on an electrifying adventure unlike any other. As Thor grapples with newfound challenges and internal conflicts, he teams up with the mighty Valkyrie and the enigmatic Guardians of the Galaxy, facing off against cosmic threats and personal demons. Amidst the chaos, Jane Foster wields the power of Mjolnir, becoming the mighty Thor herself. With exhilarating action, heartfelt emotion, and cosmic spectacle, Love and Thunder promises to be a dazzling journey of heroism, redemption, and the power of love across the realms.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BYmMxZWRiMTgtZjM0Ny00NDQxLWIxYWQtZDdlNDNkOTEzYTdlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UY2500_.jpg",
    },
    {
        "uid": "Black Panther: Wakanda Forever",
        "title": "Black Panther: Wakanda Forever",
        "popular": "popular",
        "year": 2022,
        "rating": 6.7,
        "Hero": "Hawkeye",
        "himg":"https://cdn.britannica.com/34/218334-050-759D83D7/American-actor-Jeremy-Renner-2017.jpg",
        "dlink": "https://lively-block-5b85.xipow36551427.workers.dev/1396595121/c626f8f76cfd09326fd095c7ceda2efd8d289402f3c16742fd20f87515d7dfa3964192208b5ba4747aa7029bf5f4704ffdefa0902c34751497add8be64ff6368c19f917442662a30cc1bced25daf02be845ef7ab0d3f9fb000ae3fdf9c619a7371d0bb2c6599dd8569aec7281956b10e1f804e91bd1ac937c9f6e5e33415c946f010f1946b701e6a13af9ef5a0730ee7::71e61173028fb136ec46f1adad866067",
        "images": [
            "https://i.pinimg.com/564x/6c/bc/77/6cbc77cd6ba710531c7cce9f58b9a581.jpg",

        ],
        "description": "Black Panther: Wakanda Forever pays homage to Chadwick Boseman's legacy while expanding the rich tapestry of Wakandan culture and heroism. As the nation mourns the loss of its king, T'Challa, the mantle of the Black Panther is passed to a new protector, grappling with the weight of tradition and the challenges of leadership. Against the backdrop of political intrigue and external threats, the people of Wakanda unite to defend their homeland and honor T'Challa's memory. With themes of legacy, identity, and unity, Wakanda Forever celebrates the enduring spirit of Wakanda and its remarkable heroism.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BNTM4NjIxNmEtYWE5NS00NDczLTkyNWQtYThhNmQyZGQzMjM0XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UY2500_.jpg",

    },
    {
        "id": "Spider-Man",
        "uid": "Spider-Man: No Way Home",
        "title": "Spider-Man: No Way Home",
        "year": 2021,
        "popular": "Spider-Man: No Way Home",
        "Hero": "Black Panther",
        "himg":"https://www.essence.com/wp-content/uploads/2018/03/1521472877/GettyImages-926976624.jpg",
        "images": [
            "https://i.pinimg.com/564x/5d/25/f0/5d25f0eca9681ad1a89eebc5a71e1712.jpg",
        ],
        "dlink": "https://pub-55d2d9eca98648babf4a3de0af71c353.r2.dev/2_[iMAX]%20Spider-Man.No.Way.Home.2021.IMAX.BluRay.Dual.1080p%20-%20Vegamovies.to.mkv",
        "description": "Spider-Man: No Way Home follows Peter Parker's struggle as his secret identity is exposed, unleashing chaos upon his life. With the help of Doctor Strange, he embarks on a perilous journey through the multiverse, facing familiar foes from alternate realities. As he grapples with the consequences of his actions and the burden of responsibility, Peter must confront his greatest challenge yet. Packed with mind-bending twists, epic battles, and emotional resonance, No Way Home promises to be a thrilling exploration of heroism, sacrifice, and the enduring spirit of the friendly neighborhood Spider-Man.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_FMjpg_UY4000_.jpg",
    },
    {
        "uid": "Eternals",
        "title": "Eternals",
        "dlink": "",
        "year": 2021,
        "rating": 6.3,
        "Hero": "Doctor Strange",
        "himg":"https://m.media-amazon.com/images/M/MV5BMjE0MDkzMDQwOF5BMl5BanBnXkFtZTgwOTE1Mjg1MzE@._V1_.jpg",
        "images": [
            "https://i.pinimg.com/564x/ef/7d/63/ef7d63b35410bdc116f7eb1144f0a515.jpg",
        ],
        "description":
            "Eternals introduces a celestial team of immortal beings who have secretly shaped Earths history for millennia. Tasked with protecting humanity from ancient threats, they reunite to confront the emergence of their nefarious counterparts, the Deviants. As they grapple with their purpose and identities, the Eternals face moral dilemmas and existential questions, testing the limits of their powers and bonds. With breathtaking visuals, epic scale, and diverse characters, Eternals explores themes of destiny, sacrifice, and the eternal struggle between good and evil, offering a fresh perspective on the Marvel Cinematic Universe.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMTExZmVjY2ItYTAzYi00MDdlLWFlOWItNTJhMDRjMzQ5ZGY0XkEyXkFqcGdeQXVyODIyOTEyMzY@._V1_FMjpg_UY2500_.jpg",
    },
    {
        "uid": "Shang-Chi",
        "title": "Shang-Chi and the Legend of the Ten Rings",
        "popular": "popular",
        "dlink": "https://5f61ef50c685a945364a5a3689cd8034.r2.cloudflarestorage.com/hub/2_Shang-Chi%20and%20the%20Legend%20of%20the%20Ten%20Rings%202021%20IMAX%201080p%20DSNP%20WEB-DL%20x265%20HEVC%2010bit%20%5BOrg%20Hindi%20DDP%205.1%20~192Kbps%20%2B%20English%20DDP%205.1%5D%20ESub%20~%20Vegamovi?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=fbc392f436d22304d65f4fbb2d39680b%2F20240509%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240509T170733Z&X-Amz-Expires=28800&X-Amz-SignedHeaders=host&response-content-disposition=2_Shang-Chi%20and%20the%20Legend%20of%20the%20Ten%20Rings%202021%20IMAX%201080p%20DSNP%20WEB-DL%20x265%20HEVC%2010bit%20%5BOrg%20Hindi%20DDP%205.1%20~192Kbps%20%2B%20English%20DDP%205.1%5D%20ESub%20~%20Vegamovi&X-Amz-Signature=2cb85fff43c20d6ac4119904e11bdda4221175260fea90e9849147f9848b391f",
        "year": 2021,
        "Hero": "Deadpool",
        "himg":"https://i.insider.com/5b01ca5f42e1cc72c82d50b4?width=600&format=jpeg&auto=webp",
        "images": [
            "https://i.pinimg.com/564x/17/d3/4c/17d34c7da196f155d4ecc0c85b8cdd3d.jpg",

        ],
        "rating": 7.4,
        "description": "Shang-Chi and the Legend of the Ten Rings follows martial arts prodigy Shang-Chi as he confronts his past and embraces his destiny. Drawn into the clandestine world of the Ten Rings organization, Shang-Chi must confront his father, the enigmatic Wenwu, and the dark forces he commands. With the help of allies like Katy and the powerful martial arts master, Ying Nan, Shang-Chi embarks on a thrilling adventure to prevent the Ten Rings from unleashing chaos upon the world. Packed with exhilarating action, heartfelt emotion, and cultural significance, the film redefines the superhero genre with its groundbreaking representation and storytelling.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BNTliYjlkNDQtMjFlNS00NjgzLWFmMWEtYmM2Mzc2Zjg3ZjEyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UY2500_.jpg",
    },
    {
        "id": "Avengers",
        "uid": "Avengers",
        "title": "Avengers: Endgame",
        "popular": "popular",
        "dlink": "https://c70009ee5dcecfd686d5e7795c861a01.r2.cloudflarestorage.com/hub/Avengers%20-%20Endgame%202019%20IMAX%201080p%20DSNP%20WEB-DL%20x265%20HEVC%2010bit%20%5BOrg%20DSNP%20Hindi%20DDP%205.1%20~192Kbps%20%2B%20English%20DDP%205.1%5D%20ESub%20~%20Vegamovies.NL.mkv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=919d5c775b9cf3fb9924923d0e9fa926%2F20240509%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240509T155350Z&X-Amz-Expires=28800&X-Amz-SignedHeaders=host&response-content-disposition=Avengers%20-%20Endgame%202019%20IMAX%201080p%20DSNP%20WEB-DL%20x265%20HEVC%2010bit%20%5BOrg%20DSNP%20Hindi%20DDP%205.1%20~192Kbps%20%2B%20English%20DDP%205.1%5D%20ESub%20~%20Vegamovies.NL.mkv&X-Amz-Signature=ae407bed6569df7baef37c0533553e3eb54585149510517ff32c03edfd15f5ea",
        "year": 2019,
        "rating": 8.4,
        "Hero": "Ant-Man",
        "himg":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Paul_Rudd_%28cropped%29_2.jpg/640px-Paul_Rudd_%28cropped%29_2.jpg",
        "images": [
            "https://i.pinimg.com/564x/7f/9d/df/7f9ddf2ba19e4a66420ecca261668df3.jpg",  
        ],
        "description": "Avengers: Endgame is the epic culmination of the Marvel Cinematic Universe, as the surviving heroes grapple with the aftermath of Thanos' devastating snap. With the fate of the universe at stake, the Avengers embark on a daring mission through time to gather the Infinity Stones and undo the Mad Titan's actions. Packed with emotional reunions, epic battles, and poignant farewells, Endgame delivers a satisfying conclusion while reshaping the MCU's landscape and setting the stage for a new era of heroes and adventures.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_FMjpg_UY2048_.jpg",
    },
    {
        "id": "Spider-Man",
        "uid": "Spider-Man: Far From Home",
        "title": "Spider-Man: Far From Home",
        "popular": "Spider-Man: Far From Home",
        "dlink": "https://4bd261d68ad1732159c23b2d26dfa503.r2.cloudflarestorage.com/hub/Spider-Man%20-%20Far%20from%20Home%202019%20IMAX%201080p%20WEB-DL%20x265%20HEVC%2010bit%20EAC3%205.1%20Hindi%20-%20Vegamovies.NL.mkv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=a3efc94bd8b4baf07dfea5e83db8da34%2F20240509%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240509T164254Z&X-Amz-Expires=28800&X-Amz-SignedHeaders=host&response-content-disposition=Spider-Man%20-%20Far%20from%20Home%202019%20IMAX%201080p%20WEB-DL%20x265%20HEVC%2010bit%20EAC3%205.1%20Hindi%20-%20Vegamovies.NL.mkv&X-Amz-Signature=4ee6f400bf12a6597d76b8b6337b751b635bfe9479a235c5457d9e5e287acdba",
        "year": 2019,
        "rating": 7.4,
        "Hero": "Scarlet Witch",
        "himg":"https://variety.com/wp-content/uploads/2023/06/Screen-Shot-2023-06-09-at-12.34.47-PM.png",
        "images": [
            "https://i.pinimg.com/564x/05/2a/a9/052aa95dfa5e8f97b98207b32cd300ae.jpg",
        ],
        "description": "Spider-Man: Far From Home swings Peter Parker across Europe for a much-needed vacation, but trouble follows. With Tony Stark's legacy looming large, Peter grapples with his responsibilities as both a teenager and a hero. When elemental creatures wreak havoc, he teams up with the enigmatic Mysterio to battle the emerging threats. Amidst breathtaking action and globe-trotting adventure, Peter must confront illusions, deceit, and the true meaning of heroism. Far From Home is a thrilling journey of self-discovery, friendship, and the enduring spirit of Spider-Man in the face of overwhelming odds and personal challenges.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BODJlNGFiNjctZWQ3My00ZmNhLThlNGYtNjA2ZTQ1ZGY0M2UwXkEyXkFqcGdeQXVyNTE1NjY5Mg@@._V1_FMjpg_UY2786_.jpg",
    },
    {
        "uid": "Captain Marvel",
        "title": "Captain Marvel",
        "year": 2019,
        "rating": 6.8,
        "Hero": "Captain Marvel",
        "himg": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Captain_Marvel_trailer_at_the_National_Air_and_Space_Museum_4_%28cropped%29.jpg/640px-Captain_Marvel_trailer_at_the_National_Air_and_Space_Museum_4_%28cropped%29.jpg",
        "images": [
            "https://i.pinimg.com/564x/35/39/a0/3539a0e870b971e2352aa34169d53b3b.jpg",

        ],
        "dlink": "https://pixeldrain.net/api/file/PHjxUg4x?download",
        "description": "Captain Marvel follows Carol Danvers as she navigates her past and discovers her true identity as one of the universe's most powerful heroes. With the Earth caught in the crossfire of an intergalactic conflict between two alien races, Carol teams up with a young Nick Fury to stop the impending threat. Packed with exhilarating action and empowering themes, Captain Marvel is a thrilling origin story that celebrates courage, resilience, and the indomitable spirit of a hero.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMTE0YWFmOTMtYTU2ZS00ZTIxLWE3OTEtYTNiYzBkZjViZThiXkEyXkFqcGdeQXVyODMzMzQ4OTI@._V1_FMjpg_UY2500_.jpg",
    },
    {
        "id": "Thor",
        "uid": "Thor: Ragnarok",
        "title": "Thor: Ragnarok",
        "description": "Thor: Ragnarok thrusts the God of Thunder into a cosmic adventure like never before. Stripped of his hammer and imprisoned on a distant planet, Thor must fight his way out to prevent the apocalyptic event of Ragnarok. Teaming up with old allies and new friends, including the Hulk and Valkyrie, Thor embarks on a hilarious and action-packed journey filled with colorful characters, epic battles, and witty humor. The film redefines the superhero genre with its bold visuals and irreverent tone.",
        "year": 2017,
        "Hero": "Falcon",
        "himg":"https://i0.wp.com/www.thewrap.com/wp-content/uploads/2015/10/anthony-mackie.jpg?fit=618%2C412&ssl=1",
        "images": [
            "https://i.pinimg.com/564x/b0/c2/2b/b0c22be9c3f21f63c2d8c97ca35dd28a.jpg",
        ],
        "dlink": "https://tartarus.feralhosting.com/firepig/JP/MOVIES/Thor.The.Dark.World.2013.720p.BluRay.DTS.x265.HEVC-PublicHD/Thor.The.Dark.World.2013.720p.BluRay.DTS.x265.HEVC-PublicHD.mkv",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BNDE4ZDI5ZTItMWI4My00N2NlLWJmMTQtMjgzODkyYjk5MWRiXkEyXkFqcGdeQXVyNDQxNjcxNQ@@._V1_FMjpg_UX717_.jpg",
    },
    {
        "uid": "Black Panther",
        "title": "Black Panther",
        "description": "Black Panther is a groundbreaking superhero film that transports audiences to the technologically advanced nation of Wakanda. T'Challa, heir to the throne, must navigate political intrigue and face a powerful adversary, Erik Killmonger, who challenges his claim. With the help of fierce warriors and brilliant scientists, T'Challa embraces his role as the Black Panther to protect his people and preserve their way of life. Fueled by themes of identity, legacy, and social responsibility, Black Panther is not only a thrilling action spectacle but also a cultural milestone that celebrates African heritage and inspires audiences worldwide.",
        "dlink": "https://pixeldrain.net/api/file/csAsi9ZR?download",
        "year": 2018,
        "Hero": "Winter Soldier",
        "himg":"https://d26oc3sg82pgk3.cloudfront.net/files/media/edit/image/47010/article_full%401x.png",
        "images": [
            "https://i.pinimg.com/564x/60/fe/4b/60fe4b8eb7cdf8d90397e29bca131bca.jpg"

        ],
        "rating": 7.3,
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_FMjpg_UY2048_.jpg",
    },
    {
        "id": "Avengers",
        "uid": "Avengers:Infinity War",
        "title": "Avengers:Infinity War",
        "description": "Avengers: Infinity War is a monumental crossover event that pits Earth's mightiest heroes against the cosmic threat of Thanos. Determined to obtain all six Infinity Stones and wield ultimate power, Thanos embarks on a quest of destruction that spans the universe. As the Avengers and their allies scramble to stop him, alliances are tested, sacrifices are made, and the fate of existence hangs in the balance. With breathtaking action, heart-wrenching drama, and shocking twists, Infinity War delivers an epic, emotional rollercoaster that forever alters the landscape of the Marvel Cinematic Universe",
        "year": 2018,
        "rating": 8.4,
        "Hero": "Daredevil",
        "himg":"https://i.pinimg.com/736x/fe/95/ed/fe95ed1a518e96bc76d719985705090f.jpg",
        "images": [
            "https://i.pinimg.com/564x/aa/4a/61/aa4a6134ade1362054d9456e614b3c34.jpg",

        ],
        "dlink": "https://tartarus.feralhosting.com/firepig/JP/MOVIES/Avengers.Infinity.War.2018.1080p.BRRip.5.1.HEVC.x265-GIRAYS%202.mkv",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_FMjpg_UY2048_.jpg",
    },
    {
        "id": "Ant-Man",
        "uid": "Ant-Man and the Wasp",
        "title": "Ant-Man and the Wasp",
        "description": "Ant-Man and the Wasp reunites Scott Lang and Hope van Dyne in a high-stakes, size-shifting adventure. As they race against time to rescue Hope's long-lost mother from the quantum realm, they face a formidable new adversary, Ghost, who can phase through solid matter. With inventive action sequences and comedic flair, the duo navigates through shrinking and enlarging landscapes, while balancing their personal lives and the responsibilities of being heroes. Packed with humor and heart, Ant-Man and the Wasp delivers a delightful and entertaining addition to the Marvel Cinematic Universe.",
        "year": 2018,
        "himg":"https://images.hindustantimes.com/rf/image_size_640x362/HT/p2/2016/05/04/Pictures/krysten-ritter_ff3cc41e-11d3-11e6-a855-9958039a7c6d.jpg",
        "Hero": "Jessica Jones",
        "images": [
            "https://i.pinimg.com/564x/7a/b0/b7/7ab0b7aac18a00f025c8f3faa61c934a.jpg",
        ],
        "rating": 7,
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BYjcyYTk0N2YtMzc4ZC00Y2E0LWFkNDgtNjE1MzZmMGE1YjY1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UY2500_.jpg",
    },
    {
        "id": "Captain America",
        "uid": "Captain America: Civil War",
        "title": "Captain America: Civil War",
        "description": "Captain America: Civil War ignites a clash of ideologies within the Avengers when political pressure mounts for government oversight of super-powered individuals. Steve Rogers, aka Captain America, opposes regulation, while Tony Stark, aka Iron Man, supports it. As tensions escalate and alliances fracture, the team fractures into opposing factions, leading to a devastating showdown. With thrilling action, emotional depth, and moral complexity, Civil War explores themes of accountability, friendship, and the cost of heroism, forever altering the dynamics of the Marvel Cinematic Universe and setting the stage for its future conflicts.",
        "dlink": "https://tartarus.feralhosting.com/firepig/JP/MOVIES/Captain.America.Civil.WAR.2016.1080p.HD.TC.AC3.x264-ETRG/Captain.America.Civil.WAR.2016.1080p.HD.TC.AC3.x264-ETRG.mkv",
        "year": 2016,
        "Hero": "Jessica Jones",
        "images": [
            "https://i.pinimg.com/564x/9b/99/5d/9b995d7f871457ac5fce20cafadbe12b.jpg",
        ],
        "rating": 7.8,
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZDc2MDk3NzAtMTI2My00YmQzLTkxMTktZjRkZWYyYjVkMThjXkEyXkFqcGdeQXVyNDQ5MDYzMTk@._V1_FMjpg_UX1000_.jpg",
    },
    {
        "uid": "Doctor Strange",
        "id": "Doctor Strange",
        "title": "Doctor Strange",
        "description": "Doctor Strange introduces Dr. Stephen Strange, a brilliant but arrogant neurosurgeon whose life changes forever after a car accident leaves his hands damaged. Desperate to heal, he seeks out the mystical Ancient One, plunging into a world of sorcery and alternate dimensions. Trained in the mystic arts, Strange must confront dark forces threatening reality itself. With mind-bending visuals and spiritual enlightenment, Doctor Strange is a journey of redemption and self-discovery that expands the Marvel Cinematic Universe into mystical realms.",
        "dlink": "https://b31e3cd4e7aadb8c50d06763a6cde3a1.r2.cloudflarestorage.com/hub/Doctor%20Strange%202016%20IMAX%201080p%2010bit%20DSNP%20WEB-DL%20x265%20HEVC%20%5BOrg%20Hindi%20BD%205.1%20640Kbps%20%2B%20English%20DDP%205.1%5D%20MSubs%20~%20Vegamovies.NL.mkv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=eced440c71968dbbf7b483a812d5326e%2F20240509%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240509T144453Z&X-Amz-Expires=28800&X-Amz-SignedHeaders=host&response-content-disposition=Doctor%20Strange%202016%20IMAX%201080p%2010bit%20DSNP%20WEB-DL%20x265%20HEVC%20%5BOrg%20Hindi%20BD%205.1%20640Kbps%20%2B%20English%20DDP%205.1%5D%20MSubs%20~%20Vegamovies.NL.mkv&X-Amz-Signature=11ad0d7b6493e29c7cc4f5c3f22c87c55b66008a3d735610dee14c9c360e0b38",
        "year": 2016,
        "Hero": "Iron Fist",
        "himg":"https://variety.com/wp-content/uploads/2016/02/finn-jones-iron-fist.jpg",
        "images": [
            "https://i.pinimg.com/564x/20/84/50/20845022050d6b99ae942a6ed7f13de5.jpg",
        ],
        "rating": 7.5,
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_FMjpg_UY2048_.jpg",
    },
    {
        "uid": "Guardians of the Galaxy2",
        "title": "Guardians of the Galaxy Vol. 2",
        "description": "In Guardians of the Galaxy Vol. 2, the cosmic misfits embark on a new adventure, unraveling the mysteries of Peter Quill's parentage. As they navigate through perilous encounters and personal revelations, the team forms unexpected alliances while evading relentless foes. Alongside familiar faces like Rocket, Groot, and Gamora, they encounter eccentric beings, including Ego, a celestial being claiming to be Quill's father. Amidst humor and heartache, the Guardians confront their pasts and forge deeper bonds of friendship, culminating in a cosmic battle that tests their resolve and defines their place in the universe.",
        "dlink": "https://green-bonus-ad4f.palosor7772625.workers.dev/038f84d7dd99ba828d7eda9940db85b106a0f018b8e367b19fe58be23a9ee81c77378b2736dd59496fcee0426ac0c395::ea6073d705fc89b08ae779ac10cd5216/1396595121/Guardians%20of%20the%20Galaxy%20Vol.%202%20(2017)%20IMAX%201080p%2010bit%20DSNP%20WEB-DL%20x265%20HEVC%20[Org%20Hindi%20BD%205.1%20640Kbps%20+%20English%20DDP%205.1]%20MSubs%20~%20Vegamovies.NL.mkv",
        "year": 2017,
        "Hero": "Wolverine",
        "himg":"https://static.republika.co.id/uploads/images/inpicture_slide/hugh-jackman-_170309174559-789.jpg",
        "images": [
            "https://i.pinimg.com/564x/e7/c4/b6/e7c4b6825fc6ff11cdf4d6b1ce077ccc.jpg",
        ],
        "rating": 7.6,
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_FMjpg_UX509_.jpg",
    },
    {
        "id": "Spider-Man",
        "uid": "Spider-Man:Homecoming",
        "Hero": "Ghost Rider",
        "himg":"https://www.hollywoodreporter.com/wp-content/uploads/2011/06/nicolas_cage_2011_a_p.jpg",
        "images": [
            "https://i.pinimg.com/564x/02/ad/22/02ad22978f34007131f7e8273d84c10b.jpg",

        ],
        "title": "Spider-Man: Homecoming",
        "description": "Spider-Man: Homecoming follows Peter Parker as he navigates the challenges of high school life while balancing his duties as the friendly neighborhood Spider-Man. When a new villain, Vulture, emerges, Peter must prove himself as a hero without the guidance of Iron Man. Packed with humor, heart, and thrilling action, Homecoming is a coming-of-age tale that redefines what it means to be a hero.",
        "year": 2017,
        "dlink": "https://tartarus.feralhosting.com/firepig/JP/MOVIES/Spider-Man.Homecoming.2017.1080p.BRRip.6CH.MkvCage.mkv",
        "rating": 7.4,
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BODY2MTAzOTQ4M15BMl5BanBnXkFtZTgwNzg5MTE0MjI@._V1_FMjpg_UY2048_.jpg",
    },
    {
        "id": "Captain America",
        "uid": "Captain America:The Winter Soldier",
        "title": "Captain America:The Winter Soldier",
        "description": "Captain America: The Winter Soldier thrusts Steve Rogers into a world of espionage and intrigue when a shadowy conspiracy threatens S.H.I.E.L.D. With the help of Natasha Romanoff and new ally Sam Wilson, Captain America uncovers a chilling truth: his old friend Bucky Barnes, now the brainwashed assassin Winter Soldier, is at the heart of the conspiracy. Packed with intense action and political thriller elements, the film redefines the superhero genre.",
        "year": 2014,
        "Hero": "Moon Knight",
        "himg":"https://images.fandango.com/ImageRenderer/300/0/redesign/static/img/default_poster.png/0/images/masterrepository/performer%20images/316067/OliverJackson-Cohen-2022_r.jpg",
        "images": [
            "https://i.pinimg.com/564x/e0/d1/3f/e0d13f0502fad338a02ead315e96baf3.jpg",
        "https://images.fandango.com/ImageRenderer/300/0/redesign/static/img/default_poster.png/0/images/masterrepository/performer%20images/316067/OliverJackson-Cohen-2022_r.jpg",

        ],
        "rating": 7.7,
        "dlink": "https://hubcloud.day/re/dl.php?id=eEdubFprZDByLzcxeEYyUnhoNVgyU01jMEg5VnBkN2RxNm5KVlNDMDFSWHl6cDVZMytzMjdiYUlNMXFOVjlsMUkzRjJzY212UzNWdTlFQUo0L0h2V280dW1hZ0piWlhZbGFPWGJSNzJxdFk9",
        "category": "laptops",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BYzMyN2I0NjMtYmZhZS00MWJkLWE1MTktNGM2ZDhmNDE1ZDc0XkEyXkFqcGdeQXVyNDg2NzE0MjE@._V1_FMjpg_UY2500_.jpg",
    },
    {
        "uid": "Guardians of the Galaxy",
        "title": "Guardians of the Galaxy",
        "description": "Guardians of the Galaxy introduces a motley crew of intergalactic outcasts, including Peter Quill, Gamora, Drax, Rocket, and Groot. Bonded by fate and circumstance, they embark on a daring mission to stop the power-hungry Ronan the Accuser from wielding an ancient artifact of immense destruction. Amidst exhilarating space battles and comedic escapades, the Guardians forge unlikely friendships and confront their troubled pasts. Packed with vibrant visuals, a killer soundtrack, and irreverent humor, Guardians of the Galaxy is a rollicking cosmic adventure that celebrates the power of friendship and redemption in the vastness of the universe.",
        "year": 2014,
        "dlink": "https://96d2d14554994796110e164460cafe6c.r2.cloudflarestorage.com/hub/Guardians%20of%20the%20Galaxy%202014%20IMAX%201080p%20DSNP%20WEB-DL%20x265%20HEVC%2010bit%20%5BOrg%20Hindi%20DDP%205.1%20~640Kbps%20%2B%20English%20DDP%205.1%5D%20ESub%20~%20Vegamovies.NL.mkv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=026264d434c6985b9db36fa5db2468d8%2F20240509%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240509T160416Z&X-Amz-Expires=28800&X-Amz-SignedHeaders=host&response-content-disposition=Guardians%20of%20the%20Galaxy%202014%20IMAX%201080p%20DSNP%20WEB-DL%20x265%20HEVC%2010bit%20%5BOrg%20Hindi%20DDP%205.1%20~640Kbps%20%2B%20English%20DDP%205.1%5D%20ESub%20~%20&X-Amz-Signature=fa0c7a7dc356943771b143e38d75971cd91fd205e0a3d8dabc7e8fa3979e73d6",
        "rating": 8,
        "himg": "https://static-ssl.businessinsider.com/image/5575f2f569bedd2e07e1f016-2641-1980/paul-bettany-avengers-age-of-ultron-world-premiere-1.jpg",
        "Hero": "Vision",
        "images": [
            "https://i.pinimg.com/564x/56/f4/9b/56f49bafd79b6afd1c50c4b7018b5be6.jpg",

        ],
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZTkwZjU3MTctMGExMi00YjU5LTgwMDMtOWNkZDRlZjQ4NmZhXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UY3000_.jpg",
    },
    {
        "id": "Avengers",
        "uid": "Avengers:Age of Ultron",
        "title": "Avengers:Age of Ultron",
        "Hero": "Wasp",
        "images": [
            "https://i.pinimg.com/564x/02/57/a2/0257a20845d29ec962fcf91634fee9f1.jpg",
        ],
        "popular": "popular",
        "description": "Avengers: Age of Ultron sees Earth's mightiest heroes reunite to confront a new threat: Ultron, a sentient AI created by Tony Stark. Intent on wiping out humanity, Ultron recruits twins Pietro and Wanda Maximoff to aid his cause. As the Avengers battle their own inner demons and grapple with the consequences of their actions, they must band together to stop Ultron's destructive plans. Packed with thrilling action, emotional depth, and complex themes, Age of Ultron explores the price of power and the resilience of the human spirit in the face of overwhelming odds.",
        "year": 2015,
        "dlink": "",
        "Hero": "Elektra",
        "himg": "https://www.femalefirst.co.uk/image-library/port/1000/e/elodie-yung-credit-famous-2.jpg",
        "images": [
            "https://i.pinimg.com/564x/0a/a4/73/0aa473c195d27ebb6da2ee09de7076b6.jpg",

        ],
        "rating": 7.3,
        "dlink": "",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMGRlNzA0MzUtMGU0OS00OTIyLTkwYTgtOWNkYzU2ZmVlZDljXkEyXkFqcGdeQXVyODQxMTI4MjM@._V1_FMjpg_UX764_.jpg",
    },
    {
        "uid": "Thor",
        "title": "Thor",
        "description": "Thor transports audiences to the mystical realm of Asgard, where the arrogant god of thunder, Thor, is banished to Earth by his father Odin as punishment for his reckless actions. Stripped of his powers and hammer, Mjolnir, Thor must learn humility and heroism to reclaim his birthright. As he forms unlikely alliances with scientist Jane Foster and her team, Thor faces his duplicitous brother Loki and confronts dark forces threatening both realms. Packed with epic battles, mythological lore, and themes of redemption and sacrifice, Thor is a thrilling origin story that sets the stage for the Thunder God's heroic journey.",
        "year": 2011,
        "dlink": "https://tartarus.feralhosting.com/firepig/JP/MOVIES/Thor.2011.1080p.BluRay.x264-SECTOR7/s7-thor.1080.mkv",
        "rating": 7,
        "himg":"https://cdn.justjared.com/wp-content/uploads/2020/02/jane-elton/thomas-jane-anne-heche-elton-john-oscar-party-19.jpg",
        "Hero": "Punisher",
        "images": [
            "https://i.pinimg.com/564x/28/f3/4d/28f34d8683d639a3f876f92df25847ef.jpg",

        ],
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BYzMyNzUxNjMtNjBmMi00YWRmLTk0N2QtODFjZWJmZDc5OGQwXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX800_.jpg",
    },
    {
        "id": "Captain America",
        "uid": "Captain America:The First Avenger",
        "title": "Captain America:The First Avenger",
        "description": "Captain America: The First Avenger follows Steve Rogers, a frail but determined young man who undergoes a transformative procedure, becoming the super-soldier Captain America. Tasked with defeating the villainous Red Skull and his Hydra forces during World War II, Captain America leads the fight for freedom and justice. Alongside his loyal allies, including Peggy Carter and Bucky Barnes, he confronts his own doubts and fears, embodying the ideals of heroism, sacrifice, and patriotism. Packed with thrilling action, heartfelt emotion, and historical resonance, The First Avenger is a classic tale of courage and honor.",
        "year": 2011,
        "Hero": "Quicksilver",
        "himg":"https://screencritix.com/wp-content/uploads/2013/10/aaron-johnson.jpg",
        "images": [
            "https://i.pinimg.com/564x/fe/8a/93/fe8a93cc4fc643524ef94b6e39d5a9ab.jpg",

        ],
        "rating": 6.9,
        "dlink": "https://pixeldrain.net/api/file/qpfkHNLz?download",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BNzAxMjg0NjYtNjNlOS00NTdlLThkMGEtMjAwYjk3NmNkOGFhXkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_FMjpg_UX1125_.jpg",
    },
    {
        "id": "Avengers",
        "uid": "The Avengers",
        "title": "The Avengers",
        "description": "The Avengers unites Earth's mightiest heroes—Iron Man, Captain America, Thor, Hulk, Black Widow, and Hawkeye—to combat Loki and his alien army, threatening global destruction. As they set aside their differences and forge alliances, the team faces internal conflicts and external threats, testing their mettle and unity. Packed with exhilarating action, witty banter, and iconic moments, The Avengers is a thrilling superhero spectacle that sets the standard for epic ensemble films, showcasing the power of teamwork and heroism on a grand scale.",
        "year": 2012,
        "himg":"https://static.wikia.nocookie.net/westworld/images/a/a2/Tessa_Thompson.jpg/revision/latest?cb=20161028053148",
        "Hero": "Valkyrie",
        "images": [
            "https://i.pinimg.com/564x/7f/ac/1d/7fac1dc33e1afa2d3de85223c8776dec.jpg",

        ],
        "rating": 8,
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX800_.jpg",
    },
    {
        "id": "Iron Man",
        "uid": "Iron Man3",
        "title": "Iron Man3",
        "description": "In Iron Man 3, Tony Stark grapples with post-traumatic stress disorder following the events of The Avengers. When a mysterious terrorist known as the Mandarin attacks, Stark embarks on a personal quest for vengeance. Stripped of his armor and resources, Stark relies on his ingenuity and determination to confront the true nature of the threat. Packed with intense action, unexpected twists, and emotional depth, Iron Man 3 explores Stark's resilience and the cost of being a hero in a world full of dangers.",
        "year": 2013,
        "Hero": "Shang-Chi",
        "himg":"https://www.comingsoon.net/wp-content/uploads/sites/3/2019/07/GettyImages-1163018028.jpg?w=800",
        "images": [
            "https://i.pinimg.com/564x/49/4e/78/494e78832696f6778c8a0dc7f495cf2a.jpg",
        ],
        "rating": 7.1,
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZTc0ZTJhNDktODQyYS00ZTlhLTg2NTYtYjNmYWFkZGZkOWJjXkEyXkFqcGdeQXVyOTgxMDMxNTc@._V1_FMjpg_UX600_.jpg",
    },
    {
        "id": "Thor",
        "uid": "Thor:The Dark World",
        "title": "Thor:The Dark World",
        "description": "Thor: The Dark World plunges the God of Thunder into a cosmic battle against the ancient dark elf Malekith, who seeks to unleash a destructive force known as the Aether upon the Nine Realms. As Thor reunites with Jane Foster on Earth, he must protect her while forging an uneasy alliance with his treacherous brother, Loki. Amidst realms colliding and betrayals unfolding, Thor must summon all his strength and courage to save the universe from eternal darkness. Packed with epic action, otherworldly landscapes, and themes of sacrifice and redemption, The Dark World is a thrilling cosmic adventure.",
        "year": 2013,
        "Hero": "Professor X",
        "images": [
            "https://i.pinimg.com/564x/a4/2f/12/a42f120c55a16fb20c2422f72ee54ff5.jpg",
            // "https://cdn.dummyjson.com/product-images/14/2.jpg",

        ],
        "rating": 6.8,
        "dlink": "https://pub-42e03aff938d44eb954bf548b2831f4f.r2.dev/2_Thor%20The%20Dark%20World%202013%20.1080p.BluRay.ORG.Dual.x264.ESub-%20Vegamovies.NL.mkv",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMTQyNzAwOTUxOF5BMl5BanBnXkFtZTcwMTE0OTc5OQ@@._V1_FMjpg_UX770_.jpg",
    },
    {
        "id": "Ant-Man",
        "uid": "Ant-Man",
        "title": "Ant-Man",
        "description": "Ant-Man follows Scott Lang, a skilled thief turned unlikely hero, who gains the ability to shrink in scale but increase in strength with a high-tech suit. Teaming up with inventor Hank Pym, Lang must pull off a heist to save the world from a dangerous weapon and earn redemption.",
        "year": 2015,
        "Hero": "Cyclops",
        "images": [
            "https://i.pinimg.com/564x/54/e5/40/54e54004ca958774d0267c2e5916d810.jpg",
            // "https://cdn.dummyjson.com/product-images/14/2.jpg",

        ],
        "rating": 4.25,
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMjM2NTQ5Mzc2M15BMl5BanBnXkFtZTgwNTcxMDI2NTE@._V1_FMjpg_UX488_.jpg",
    },
    {
        "id": "X-Men",
        "uid": "The Wolverine",
        "title": "The Wolverine",
        "year": 2013,
        "dlink": "https://07a85c3a3ae2f27687620fa5b4c71159.r2.cloudflarestorage.com/hub/6%20X-Men.6.The.Wolverine.2013.1080p.Dual.Audio.Hin-Eng.Vegamovies.Nl.mkv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=7c370d175c80e11eb4386b58ff6496db%2F20240509%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240509T173819Z&X-Amz-Expires=28800&X-Amz-SignedHeaders=host&response-content-disposition=6%20X-Men.6.The.Wolverine.2013.1080p.Dual.Audio.Hin-Eng.Vegamovies.Nl.mkv&X-Amz-Signature=0343ce341701f087f836ac2ee15ebd1ff328077b5c2eb3c1dcd63257d58f5f6b",
        "Hero": "Jean Grey ",
        "images": [
            "https://i.pinimg.com/564x/70/41/0e/70410efa0ce31709ac748609eaf1d1ea.jpg",
            // "https://cdn.dummyjson.com/product-images/14/2.jpg",

        ],
        "rating": 6.7,
        "description": "The Wolverine sees Logan, aka Wolverine, seeking solace in Japan after the events of X-Men: The Last Stand. Amidst political intrigue and Yakuza violence, Logan faces his own mortality and confronts a powerful enemy, the Silver Samurai. Stripped of his healing factor, Logan must rediscover his inner strength as he battles foes old and new in a thrilling and emotionally charged adventure that tests his limits.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BOTI1OWE1YzMtZTFiZC00NDkxLTk3NjAtYTg5NDc0OWE2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_FMjpg_UX800_.jpg",
    },
    {
        "id": "Spider-Man",
        "uid": "The Amazing Spider-Man2",
        "title": "The Amazing Spider-Man2",
        "year": 2014,
        "Hero": "Beast",
        "images": [
            "https://i.pinimg.com/564x/42/d5/b9/42d5b914323f43b06391867631207309.jpg",
            // "https://cdn.dummyjson.com/product-images/14/2.jpg",

        ],
        "rating": 6.6,
        "dlink": "https://pub-8942bffa33b34614827f33cab6311afb.r2.dev/The.Amazing.Spider.Man.2.2014.1080p.Dual.Audio.Hin-Eng.Vegamovies.NL.mkv",
        "description": "The Amazing Spider-Man 2 continues Peter Parker's journey as he battles new villains, including Electro and the Green Goblin, while struggling with his relationship with Gwen Stacy. As secrets from his past unravel, Peter must confront his destiny as Spider-Man and the responsibilities that come with it. Packed with high-flying action, heartfelt romance, and emotional stakes, The Amazing Spider-Man 2 is a thrilling and poignant chapter in the web-slinger's saga",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BOTA5NDYxNTg0OV5BMl5BanBnXkFtZTgwODE5NzU1MTE@._V1_FMjpg_UY3000_.jpg",
    },
    {
        "id": "X-Men",
        "uid": "X-Men: Days of Future Past",
        "title": "X-Men: Days of Future Past ",
        "year": 2014,
        "rating": 7.9,
        "dlink": "https://falling-frog-222e.sipijo45025880.workers.dev/1396595121/4b62681f3e859bc8354e54d2fd08c197e189fc2c9d9add31baa9010268a2a69f47315d14013ad8250f3ccaa50c795ad12e9d330faedf0ea2848677d35ae8bea3d6ed180df262cfffbdb619ad79fdfacac5fff1677beb17896b775801bab20f9c11378cd876de4a1e01255a590d171be000c04aaf3ccda06f935456ac071cbd78bd991fb8737f7f5adbd7173e3d5ec51b::b88c070322bda4e3d835be991ca68f07/X-Men.7.Days.Of.Future.Past.2014.720p.Dual.Audio.Hin-Eng.Vegamovies.NL.mkv",
        "description": "X-Men: Days of Future Past sees the mutants facing extinction in a dystopian future. They send Wolverine's consciousness back in time to prevent a chain of events leading to this catastrophe. Racing against time, Wolverine must unite the young and old versions of the X-Men to change the course of history. Packed with epic action and emotional depth, it's a gripping tale of survival and redemption.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BNjk3MGZhMjEtOTM4NC00NzE2LTk2NzctZDc4YTUwN2E3NDhhXkEyXkFqcGdeQXVyNDc2NjEyMw@@._V1_FMjpg_UY4724_.jpg",
    },
    {
        "uid": "Big Hero6",
        "title": "Big Hero6",
        "year": 2014,
        "rating": 7.8,
        "description": "Big Hero 6 introduces Hiro Hamada, a young robotics prodigy, and his inflatable healthcare companion Baymax. When a masked villain threatens the futuristic city of San Fransokyo, Hiro assembles a team of unlikely heroes, including his friends and Baymax, to save the day. Packed with heart, humor, and high-tech action, the film explores themes of friendship, loss, and perseverance. Through their adventures, the heroes learn the true meaning of heroism and discover that together, they can overcome any obstacle. Big Hero 6 is a heartwarming and exhilarating animated adventure for all ages.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMDliOTIzNmUtOTllOC00NDU3LWFiNjYtMGM0NDc1YTMxNjYxXkEyXkFqcGdeQXVyNTM3NzExMDQ@._V1_FMjpg_UY2835_.jpg",
    },
    {
        "uid": "Fantastic Fourx",
        "title": "Fantastic Four",
        "year": 2015,
        "rating": 4.3,
        "description": "The Fantastic Four, a team of brilliant scientists, embark on a space mission that results in their exposure to cosmic radiation, granting them extraordinary powers. Reed Richards becomes the stretchable Mr. Fantastic, Sue Storm gains invisibility and force field abilities as the Invisible Woman, Johnny Storm becomes the fiery Human Torch, and Ben Grimm transforms into the rock-like Thing. As they grapple with their newfound abilities and their arch-nemesis, Victor Von Doom, they must learn to work together to protect Earth from threats both terrestrial and cosmic in this iconic Marvel superhero team's origin story.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMTk0OTMyMDA0OF5BMl5BanBnXkFtZTgwMzY5NTkzNTE@._V1_FMjpg_UY2048_.jpg",
    },
    {
        "id": "Deadpool",
        "uid": "Deadpool",
        "title": "Deadpool",
        "year": 2016,
        "rating": 8,
        "description": "Deadpool introduces Wade Wilson, a former special forces operative turned mercenary who undergoes an experimental procedure to cure his cancer. The treatment leaves him disfigured but grants him accelerated healing powers and a twisted sense of humor. Embracing his alter ego, Deadpool, he embarks on a quest for revenge against those who wronged him. Packed with irreverent humor, fourth-wall-breaking antics, and over-the-top action, Deadpool is a hilarious and unapologetically R-rated superhero romp.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BYzE5MjY1ZDgtMTkyNC00MTMyLThhMjAtZGI5OTE1NzFlZGJjXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UY3000_.jpg",
    },
    {
        "id": "X-Men",
        "uid": "X-Men: Apocalypse",
        "title": "X-Men: Apocalypse",
        "year": 2016,
        "rating": 9,
        "dlink": "https://calm-band-dfb0.nesoci12838715.workers.dev/1396595190/85d0e33304e85f033748fd7c992362a4dc874a36dcc63fb4a7a5bdb768549288b82ac01c0891160ff1a62a7402be24b1b3de252899dbc4a012659a3ad9a4c928131c4dc9a5b542cb905fa62ecd75b8268ff9716034d282cfedcbd6bf759f616493ffeca587a25fa170a19b5ba24d98b80af11881a48c31d7384f811f7255d320::6747b6342c06c3681a5bfe93eb61d9b2/X-Men.9.Apocalypse.2016.720p.Dual.Audio.Hin-Eng.Vegamovies.Nl.mkv",
        "description": "X-Men: Apocalypse follows the mutant team as they face their most formidable foe yet: Apocalypse, the world's first mutant. Awakened after millennia, Apocalypse seeks to cleanse humanity and rule the world with his Four Horsemen. As chaos ensues, Professor X and Raven lead the X-Men in a desperate battle to save humanity. Packed with epic action, stunning visuals, and emotional depth, the film explores themes of power, redemption, and the enduring struggle between good and evil in the mutant world.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMjU1ODM1MzYxN15BMl5BanBnXkFtZTgwOTA4NDE2ODE@._V1_FMjpg_UX1015_.jpg",
    },
    {
        "uid": "Logan",
        "title": "Logan",
        "year": 2017,
        "rating": 8.1,
        "description": "Logan depicts an aged and weary Wolverine in a dystopian future where mutants are near extinction. Caring for a frail Professor X, Logan's secluded life is disrupted when a young mutant girl, Laura, enters his world, pursued by dark forces. With the fate of mutantkind at stake, Logan embarks on a final, harrowing journey of redemption and self-discovery. Packed with brutal action, poignant drama, and a sense of finality, Logan is a raw and emotional farewell to Hugh Jackman's iconic portrayal of the Wolverine.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZDc0MGM3MWQtZTk1Yi00ZjE4LWExZDMtYjIyNWQzN2VlM2ViXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_FMjpg_UY2346_.jpg",
    },
    {
        "id": "Deadpool",
        "uid": "Deadpool2",
        "title": "Deadpool2",
        "year": 2018,
        "rating": 7.6,
        "description": "Deadpool 2 sees the irreverent anti-hero Wade Wilson, aka Deadpool, forming the X-Force to protect a young mutant from the time-traveling soldier Cable, who seeks to alter the future. Amidst his mission, Deadpool faces personal loss and redemption while unleashing his signature humor and unorthodox tactics. Packed with even more fourth-wall-breaking antics, outrageous action, and pop culture references, Deadpool 2 delivers another hilarious and action-packed adventure that solidifies Deadpool as one of the most unconventional superheroes in the genre.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMTQwMjFlN2EtNTQ2Mi00MGQ2LTg4MTAtYzlkMGUyNmZhODczXkEyXkFqcGdeQXVyNzAwNjg1MTc@._V1_FMjpg_UX992_.jpg",
    },
    {
        "uid": "Venom",
        "title": "Venom",
        "year": 2018,
        "rating": 6.6,
        "description": "Venom follows Eddie Brock, a disgraced journalist who becomes host to an alien symbiote, granting him superhuman abilities. As he struggles to control the symbiote's violent impulses, Brock must confront the sinister Life Foundation and its leader, Carlton Drake, who seeks to exploit the symbiotes for his own gain. Packed with intense action, dark humor, and a conflicted anti-hero, Venom is a thrilling and unconventional tale of redemption and survival in a world of alien threats and moral ambiguity.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZTc5MmFkOTctYzY4Yi00NTRiLTg2NzEtYjQ4MWMyMGVhZDM2XkEyXkFqcGdeQXVyMTgxOTIzNzk@._V1_FMjpg_UY2000_.jpg",
    },
    {
        "id": "Spider-Man",
        "uid": "Spider-Man:Spider-Verse ",
        "title": "Spider-Man:A new universe ",
        "dlink": "https://tartarus.feralhosting.com/firepig/JP/MOVIES/Spider-Man.Into%20the%20Spider-Verse.2019.1080p.WEB-DL.H264.AC3-EVO%5BEtHD%5D.mkv",
        "year": 2018,
        "rating": 8.4,
        "description": "Spider-Man: Into the Spider-Verse introduces Miles Morales, a teenager who gains spider-like powers and must navigate a multiverse of Spider-People. Teaming up with various incarnations of Spider-Man from alternate dimensions, Miles embarks on a journey to stop the villainous Kingpin from destroying reality. Packed with stunning animation, heartfelt storytelling, and diverse characters, Into the Spider-Verse redefines the superhero genre with its inventive visuals and exploration of themes like identity, heroism, and the power of embracing one's uniqueness.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZmY5OTM3ODctZDI2ZS00Y2UzLWI5MmEtNjYwZDRmMjg4NzA2XkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_FMjpg_UX1131_.jpg",
    },
    {
        "uid": "Dark Phoenix",
        "title": "Dark Phoenix",
        "year": 2019,
        "rating": 5.7,
        "dlink": "https://cold-sun-26c6.jisepe43516660.workers.dev/1396595121/9b9a67a756877ef5344d8693c7abf5fe46370f7af529be035ce2ef8a3f2bdd3bacd1d1b6554e8c315c4b63191b92436891b728fe5c9cdf5e9699db9d98aa4a1f64bdb659864c119d89de0685a6683ef7974924f419b253c497449546a010be3911eff25baac8f3932b7a639667a39f461eabbecdeeb0343d41d2aaffbf9cadf7::5b218dee546f0b9236105732325e30fc/X-Men.Dark.Phoenix.2019.720p.Bluray.Hindi.English.Vegamovies.to.mkv",
        "description": "Dark Phoenix follows the X-Men as they face their greatest challenge yet when Jean Grey, one of their own, is consumed by a cosmic force that transforms her into the immensely powerful Dark Phoenix. As Jean struggles with her newfound abilities and inner turmoil, the X-Men must confront their friend's uncontrollable power while facing external threats, including alien forces led by Vuk. Packed with intense action, emotional depth, and themes of power and redemption, Dark Phoenix is a gripping and poignant chapter in the X-Men saga.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMmZmYTgwZGItNDIxMS00MmRkLWEzODQtYTllNzM0ZWE1NmQ5XkEyXkFqcGdeQXVyODQzNTE3ODc@._V1_FMjpg_UY2047_.jpg",
    },
    {
        "uid": "Black Widow",
        "title": "Black Widow",
        "dlink": "https://57c5a1b9626043b3fc4e5e3abd9b0be2.r2.cloudflarestorage.com/hub/2_Black%20Widow%202021%20IMAX%201080p%2010bit%20DSNP%20WEB-DL%20x265%20HEVC%20%5BOrg%20DSNP%20Hindi%20DDP%205.1%20192Kbps%20%2B%20English%20DDP%205.1%5D%20MSubs%20~%20Vegamovies.NL.mkv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=6fc0d9c99201452f4da06e233482c205%2F20240509%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240509T170120Z&X-Amz-Expires=28800&X-Amz-SignedHeaders=host&response-content-disposition=2_Black%20Widow%202021%20IMAX%201080p%2010bit%20DSNP%20WEB-DL%20x265%20HEVC%20%5BOrg%20DSNP%20Hindi%20DDP%205.1%20192Kbps%20%2B%20English%20DDP%205.1%5D%20MSubs%20~%20Vegamovies.NL.mkv&X-Amz-Signature=0a18cb05923169aacca8fe2f2f7e58078840f8669bb1429cd58d1b77267b91cb",
        "year": 2021,
        "rating": 7.6,
        "description": "Black Widow delves into Natasha Romanoff's past as she confronts her former life as a spy and assassin. Tasked with stopping a dangerous conspiracy linked to her past, Natasha reunites with her estranged family of fellow operatives. As she battles powerful adversaries, Natasha must come to terms with her history and redefine her identity as a hero. Packed with thrilling action and emotional depth, Black Widow is a gripping espionage thriller that explores Natasha's journey of redemption.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZjk3ZjQ2OWItYzYwMC00ZmNlLThlMDEtNmNmNjMzZjVhZmRkXkEyXkFqcGdeQXVyMTI0NTE1Njg4._V1_FMjpg_UX675_.jpg",
    },
    {
        "uid": "Morbius",
        "title": "Morbius",
        "year": 2022,
        "rating": 5.1,
        "description": "Morbius follows Dr. Michael Morbius, a brilliant but afflicted biochemist who, in his desperate quest to cure his rare blood disease, inadvertently transforms himself into a vampire-like creature. As he grapples with his newfound abilities and insatiable thirst for blood, Morbius becomes a hunted man, pursued by both law enforcement and supernatural threats. Amidst his struggle for survival, Morbius seeks to harness his powers for good, but risks succumbing to the darkness within. Packed with atmospheric tension and moral ambiguity, Morbius is a gripping tale of horror, tragedy, and the blurred lines between heroism and villainy.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZmVlNzkzNWYtNmIxZi00NjI1LWI1NDktNzQ2ZjFiNjc2ZjY0XkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_FMjpg_UY720_.jpg",
    },
    {
        "id": "Spider-Man",
        "uid": "Spider-Man: Across",
        "title": " Spider-Man: Across the Spider-Verse",
        "year": 2023,
        "rating": 8.6,
        "dlink": "https://hubcloud.day/re/dl.php?id=Y2s3N0lEYXFOTkVqdEdya2dDOFZJamdXUUhNMWN6SFhSVXN5SGh0aHU1OHlpamhTSFRDd0FtNDRxQzhNbXdUbVp4WElJcjVUNVM5R08rejdDekF2NHFkL3E0MHNZZmlOMVQ0Q3hqSDlmaFU9",
        "description": "Spider-Man: Across the Spider-Verse continues the story of Miles Morales as he navigates the multiverse, encountering alternate versions of Spider-People. Joined by Gwen Stacy, they face a new threat that challenges their very existence. Packed with groundbreaking animation, exhilarating action, and heartfelt storytelling, Across the Spider-Verse promises to expand the Spider-Verse in exciting and unexpected ways.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMzI0NmVkMjEtYmY4MS00ZDMxLTlkZmEtMzU4MDQxYTMzMjU2XkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_FMjpg_UY1929_.jpg",
    },
    {
        "uid": "Madame Web",
        "title": "Madame Web",
        "year": 2024,
        "rating": 3.8,
        "description": "Madame Web, a mysterious psychic with precognitive abilities, navigates the complexities of the multiverse, offering guidance to Spider-People across different dimensions. Tethered to her web-like apparatus, she serves as a mentor and seer, aiding heroes in their struggles against cosmic threats. With her enigmatic wisdom and connection to the web of fate, Madame Web plays a pivotal role in shaping the destiny of Spider-People and the course of the multiverse itself.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZGIxMzdhNzgtOGM3MS00YjE5LThiMGQtMjc5ODI4MjkyYjc2XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_FMjpg_UX1080_.jpg",
    },
    {
        "id": "X-Men",
        "uid": "X-Men: First Class",
        "title": "X-Men: First Class",
        "year": 2011,
        "rating": 7.7,
        "dlink": "https://green-queen-efac.pohat648876715.workers.dev/1396595121/98da9fe22d3f0744d2ea3054193261cb4418aed5ff19c0a1ad08fdb2b47b4081b0215158443ea000aeb6bb39257f7537202c4b5404ceec2d76e967dc03b9288e58b6a74d300fdeee553e37edc54e1901ceaf38281e0d53b6bb02d1d3f873cfc6d3792fa543a1c43c385bf5addcebc953cb5606a42a873ba562a0b8e92643b930::2b1d3e8aa73b3510fde8adea4ad5fff1/2_X-Men.5.First.Class.2011.720p.Dual.Audio.Hin-Eng.Vegamovies.Nl.mkv",
        "description": "X-Men: First Class explores the origins of the mutant team, set against the backdrop of the Cuban Missile Crisis. Charles Xavier and Erik Lensherr, later known as Professor X and Magneto, respectively, join forces to recruit and train a new generation of mutants. As tensions rise between the two leaders' differing philosophies, they must unite to stop the mutant supremacist Sebastian Shaw and his Hellfire Club. Packed with exhilarating action, complex characters, and thematic depth, First Class is a riveting and stylish reboot of the X-Men franchise.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BNDQ1NDA3NjgyOV5BMl5BanBnXkFtZTcwMTY5MDQ1Ng@@._V1_FMjpg_UX369_.jpg",
    },
    {
        "id": "Ghost Rider",
        "uid": "Ghost Rider: Spirit of Vengeance",
        "title": "Ghost Rider: Spirit of Vengeance",
        "year": 2011,
        "rating": 4.3,
        "description": "Ghost Rider: Spirit of Vengeance follows Johnny Blaze, cursed to become the fiery, vengeance-seeking Ghost Rider, as he battles the demonic forces of Blackout and the devilish Roarke, who seek to possess a young boy named Danny. Tasked with protecting Danny and his mother Nadya, Blaze grapples with his inner turmoil while unleashing hellish fury upon his enemies. Packed with intense action, supernatural thrills, and dark, atmospheric visuals, Spirit of Vengeance is a fiery ride through the depths of the underworld.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZDEwMGRmY2YtZTFmNy00YmFkLWFlZGItZGE0ZjNiMjRmZjZlXkEyXkFqcGdeQXVyMTUyOTc1NDYz._V1_FMjpg_UY3000_.jpg",
    },
    {
        "id": "Spider-Man",
        "uid": "The Amazing Spider-Man",
        "title": "The Amazing Spider-Man",
        "year": 2012,
        "rating": 6.9,
        "dlink": "https://hubcloud.day/re/dl.php?id=Y2s3N0lEYXFOTkVqdEdya2dDOFZJajRlK1hudnVEbWdWenB3bU9xSjU5d0Iyc0ZqL2JDOE5YRHBvekRpSVFCQXFaTEhILzFmcmhCVFIwSmRoUFdtUU5IVWJGNnV0M2VITnVDWkQzc1FnQnM9",
        "description": "The Amazing Spider-Man reimagines Peter Parker's origin story as he grapples with newfound powers and the responsibility that comes with them. Donning the iconic suit, Peter seeks to uncover the truth behind his parents' disappearance while battling his father's former colleague, Dr. Curt Connors, who transforms into the monstrous Lizard. Packed with action, romance, and emotional depth, The Amazing Spider-Man is a fresh take on the beloved superhero's journey of self-discovery and heroism.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMjMyOTM4MDMxNV5BMl5BanBnXkFtZTcwNjIyNzExOA@@._V1_FMjpg_UY2048_.jpg",
    },
    {
        "id": "Hulk",
        "uid": "The Incredible Hulk",
        "title": "The Incredible Hulk",
        "dlink": "",
        "year": 2008,
        "rating": 6.6,
        "description": "The Incredible Hulk delves into the tragic tale of scientist Bruce Banner, who, after a failed experiment, transforms into the rage-filled Hulk whenever angered. On the run from the military and hunted by General Ross, Banner seeks a cure while wrestling with his inner demons. Amidst his struggles, he must confront the formidable Abomination, a monstrous foe created through a similar experiment. Packed with heart-pounding action, emotional depth, and stunning CGI, The Incredible Hulk is a thrilling exploration of power, redemption, and the human condition in the face of uncontrollable fury.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMTUyNzk3MjA1OF5BMl5BanBnXkFtZTcwMTE1Njg2MQ@@._V1_FMjpg_UY2048_.jpg",
    },
    {
        "id": "Iron Man",
        "uid": "Iron Man 2",
        "title": "Iron Man 2",
        "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
        "year": 2010,
        "discountPercentage": 17.94,
        "rating": 6.9,
        "description": "Iron Man 2 sees Tony Stark confronting new challenges as he battles his own mortality due to the toxic palladium in his chest arc reactor. Meanwhile, he faces off against Ivan Vanko, aka Whiplash, and struggles with government pressure to share his Iron Man technology. Packed with action, humor, and character development, Iron Man 2 further explores Tony Stark's journey as",
        "dlink": "https://tartarus.feralhosting.com/firepig/JP/MOVIES/Iron.Man.2.2010.Bluray.1080p.DTS-HD.x264-Grym.mkv",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZGVkNDAyM2EtYzYxYy00ZWUxLTgwMjgtY2VmODE5OTk3N2M5XkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_FMjpg_UX1200_.jpg",
    },
    {
        "uid": "Howard the Duck",
        "title": " Howard the Duck",
        "year": 1986,
        "rating": 4.7,
        "description": " ",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMGE5YTg3ZWMtYTdiOS00YTdlLWIzYTQtMDM0OWM0MmRlZDA4XkEyXkFqcGdeQXVyNjc5NjEzNA@@._V1_FMjpg_UY3915_.jpg",
    },
    {
        "uid": "The Punisher",
        "title": "The Punisher",
        "year": 1989,
        "rating": 5.6,
        "description": "The Punisher follows Frank Castle, a former Marine turned vigilante, as he wages a brutal war on crime after his family is tragically murdered. Armed with military skills and an unrelenting thirst for vengeance, Castle becomes the ruthless anti-hero known as the Punisher. Blurring the lines between justice and revenge, he takes on the criminal underworld while grappling with his own moral code and inner demons. Packed with intense action, gritty realism, and ethical dilemmas, The Punisher is a dark and compelling exploration of vigilantism.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMDA3NjJlNjMtN2YzOS00YmJiLWFmNDYtNjA2MDU3M2RjZDk5XkEyXkFqcGdeQXVyMDI4NjM1MQ@@._V1_FMjpg_UX484_.jpg",
    },
    {
        "id": "Iron Man",
        "uid": "Iron Man",
        "title": "Iron Man",
        "year": 2008,
        "rating": 4.69,
        "category": "movie",
        "descrption": "Iron Man is a thrilling superhero film that follows the journey of Tony Stark, a genius inventor and billionaire industrialist, who transforms into the armored superhero Iron Man after being captured by terrorists. With his newfound technology, Stark fights against evil forces while grappling with his own inner demons and responsibilities. Directed by Jon Favreau and starring Robert Downey Jr., the film blends action, humor, and character development seamlessly, making it a groundbreaking entry in the Marvel Cinematic Universe. As Stark confronts his past and battles formidable enemies, Iron Man delivers an electrifying tale of redemption, heroism, and technological innovation.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMTA3OTg5NjUxNTdeQTJeQWpwZ15BbWU3MDg0MDE3NTQ@._V1_FMjpg_UX426_.jpg",
    },
    {
        "uid": "The Fantastic Four",
        "title": "The Fantastic Four",
        "year": 1994,
        "rating": 3.8,
        "description": "The Fantastic Four portrays the origin story of a team of extraordinary individuals granted incredible powers after exposure to cosmic radiation. Reed Richards, Sue Storm, Johnny Storm, and Ben Grimm become Mr. Fantastic, the Invisible Woman, the Human Torch, and the Thing, respectively. Together, they harness their newfound abilities to protect humanity from threats while grappling with their own personal struggles and conflicts. Packed with action, adventure, and a sense of family, The Fantastic Four exemplifies the power of teamwork and resilience in the face of adversity, shaping them into iconic heroes of the Marvel Universe.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZmQ0ZjljOWItZDA1Yy00ZjUyLThhYzEtNWFhZmM3YTA0ODVkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UY2949_.jpg",
    },
    {
        "uid": "Blade",
        "title": "Blade",
        "year": 1998,
        "rating": 7.1,
        "description": "Blade chronicles the journey of Eric Brooks, a half-vampire, half-human hybrid known as the Daywalker. Driven by a thirst for vengeance against vampires for his mother's death, Blade becomes a skilled vampire hunter. Armed with martial arts prowess and an array of weapons, he wages a relentless war against the undead. As he navigates the shadows of the night, Blade confronts his own inner demons while protecting humanity from the supernatural forces that threaten to plunge the world into darkness.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMDY1NzRlNDQtMTZiNC00ZTlkLThjYWUtNzE5OTdiNzk0MDI0XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_FMjpg_UX1001_.jpg",
    },
    {
        "id": " X-Men",
        "uid": " X-Men",
        "title": " X-Men",
        "year": 2000,
        "dlink": "https://video-downloads.googleusercontent.com/ADGPM2nG_yYC2Im8KxeQyEVD2s16FJWgoHZ2ew47f56E_UiQsesAAOAP3FnoZ5BRKxCOOs95YfiDClVoZc7zpl04agV5Dc4suxbG5LJFJlfgtbE1Lpq4hETt0V_wrqg24BnWzFVAJ17Zn-AMwABj9KXi8Gz-qLg4GeCkvqGRZHEJg3Df8oPCO705KCTOtnH9PYmhVkW_esbDb-eZvFR8EQKqLkS3yLMZeipRslYWfnV_Uz6w8r8ARM6y3aPLL8-hFGqZjWiImZkSYJJDHvxrju_ryZ_gPgoNWDWo-hnzg87AMQUSrXaaUK48rZO6YNp5TCKUKk3tN7QazWFliMqU0ky9rLajk3-8TMPrtg1rrR80nw7z7hkNFCbs2bfwV-pv93pKLEapyCG1zk80WVgfv0-sdmRXdfTUXnLcEtT5MWXVtvyGhSAcdGboxSc9gPsAEzmEq0boX9-edXuuLCIsSr0ikW0XqQWb0jEU3h48eL_TzNITUFs_n_rl5ALkqQGM78KTIYbKqRyTElmaW8ReBcQoCabMW8ons6lv5DsnzOKsVOX_s9ZvY6oDTd1_89k1r88K4jGOvGL3Zdd0SictFKrDncfpK9q9cxqbPsKZjc8HMmc7Z9rdz9CBQgq228CFaXT6ScLGvpQTkqu44m85MNFOjHP3Y4QFDacimRzRVCS4i7rShZPk5l4fjmNIuQb5yRPUx43FPP9T8fXs2TEo4_ZwSBXFpT6laUCWJgtNSNg_MtJYpK0TzoA_ponotmGVul_7pFr_jTB-8MoF0NiqehtAQp5TzXuT_GjSbiaMwDsqd-buoQEF4QxjqM5wCtRwHR7TZsuIf0CQqTFTOXt7GR4Xyw3Ap5uBEE3q0PvFSSIV6ZFzW6Oz5IG-aSFmcWjvSmkQiV0B9nFNdQKDcHzPhIQ-e52Oavz5XORXnBnXyvGBdCydVPzmDCeiYblw8f4sHdFzgBcs_G7isG2Spuf497t8ue75TzkJwc67Vr8bxz-OPXdkPoufM50qvg0cSxbpRKsjnCXO9BWa1tjEp82RyvPfzGyis-Q7igAUzREq49NMF4rqwxt8kNC1XPWcq4cZ4LwEsHBzoUhKR8S-xewTp-YmX2pDfvqD1wZLDt1Gnul4qLGcJ6NasjFHfXHC3T1BmuD20JWNsezq",
        "rating": 7.3,
        "description": "X-Men follows a group of mutants, born with extraordinary abilities, who struggle to coexist with humanity. Led by Professor Charles Xavier, they seek to protect a world that fears and hates them, while also battling their own internal conflicts and external threats, including the mutant supremacist Magneto. Packed with action, drama, and themes of prejudice and acceptance, X-Men explores the eternal struggle between those who fear differences and those who embrace diversity.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZmIyMDk5NGYtYjQ5NS00ZWQxLTg2YzQtZDk1ZmM4ZDBlN2E3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1081_.jpg",
    },
    {
        "uid": "Blade II",
        "title": "Blade II",
        "year": 2002,
        "rating": 6.7,
        "description": "Blade II sees the Daywalker teaming up with vampire enemies to combat a new breed of creatures, the Reapers, threatening both humans and vampires. As Blade navigates treacherous alliances and battles insurmountable odds, he must confront his deepest fears and embrace his destiny as humanity's last hope against the dark forces that seek to engulf the world in eternal night.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BOWVjZTIzNDYtNTBlNC00NTJjLTkzOTEtOTE0MjlhYzI2YTcyXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_FMjpg_UX800_.jpg",
    },
    {
        "id": "Spider-Man",
        "uid": "Spider-Man universe",
        "title": "Spider-Man",
        "year": 2002,
        "rating": 7.4,
        "dlink": "https://broken-truth-8f91.jayet820929517.workers.dev/1396595190/9ab51662a7026cc7390e8e3ae50800bda7837393c64489141d767c75c987feb166ec92c892dfbac441878bc8e8a0ce5d673d92adc0e42e06fc2635f9b6723b913e29a152b061017bed63cae86b87d50138327b8b9d75d1e0d03b977770461d3cbdb70079f6f8512d8bf08ae196725419::5bcaba5a6f603ef948e0469bdf61c72a/SpiderMan.2002.720p.Dual.Audio.Hin-Eng.Vegamovies.NL.mkv",
        "description": "Spider-Man follows the journey of Peter Parker, an ordinary teenager who gains spider-like abilities after being bitten by a genetically altered spider. Embracing his newfound powers, Peter becomes the masked vigilante known as Spider-Man, swinging through the streets of New York City to fight crime and protect the innocent. As he grapples with his dual identity, Peter faces formidable villains, including the Green Goblin and Doctor Octopus, while learning valuable lessons about responsibility, sacrifice, and the true meaning of heroism. Packed with thrilling action, heartfelt emotion, and iconic moments, Spider-Man is a timeless superhero classic.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BZDEyN2NhMjgtMjdhNi00MmNlLWE5YTgtZGE4MzNjMTRlMGEwXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_FMjpg_UX511_.jpg",
    },
    {
        "uid": "Daredevil",
        "title": "Daredevil",
        "year": 2003,
        "rating": 5.3,
        "description": "Daredevil follows Matt Murdock, a blind lawyer with heightened senses, who moonlights as the masked vigilante Daredevil, fighting crime in Hell's Kitchen, New York City. Driven by a desire for justice and haunted by the murder of his father, Daredevil battles corrupt officials and ruthless criminals, including the deadly Kingpin. As he navigates the complexities of his dual life, Murdock must confront his inner demons while protecting his city from darkness and despair, one night at a time.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BYWMyNDA4NzQtNGFiZi00ODVlLWFkYTktZTVhNzAxMmYzZjk0XkEyXkFqcGdeQXVyNzI1NzMxNzM@._V1_FMjpg_UX680_.jpg",
    },
    {
        "id": "X-Men",
        "uid": "X-Men2",
        "title": "X-Men2",
        "year": 2003,
        "rating": 7.4,
        "description": "In X-Men 2, tensions escalate between mutants and humans as a mutant-hating military leader launches a ruthless attack on Xavier's School for Gifted Youngsters. Wolverine and the X-Men must unite with former enemies to survive and uncover a government conspiracy aimed at eradicating mutantkind. Faced with betrayal and peril, they confront their own identities and the limits of their powers. As alliances shift and battles rage, the fate of both mutants and humanity hangs in the balance in this thrilling sequel packed with action, drama, and deep themes of acceptance and belonging.",
        "dlink": "https://pub-88a4231250aa40238dcee4cd6141fc2b.r2.dev/X-Men.2.United.2003.1080p.Dual.Audio.Hin-Eng.Vegamovies.Nl.mkv",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BNDk0NjYxMzIzOF5BMl5BanBnXkFtZTYwMTc1MjU3._V1_FMjpg_UX485_.jpg",
    },
    {
        "id": "Hulk",
        "uid": "Hulk",
        "title": "Hulk",
        "dlink": "",
        "year": 2003,
        "rating": 5.6,
        "description": "X-Men 2 sees the mutant team facing a new threat as Colonel William Stryker launches a genocidal attack on mutants, targeting Professor Xavier's school. With the stakes higher than ever, the X-Men unite with former foes Magneto and Mystique to combat this common enemy. As secrets are revealed and alliances tested, Wolverine delves into his own past while the fate of mutantkind hangs in the balance. Packed with intense action, emotional depth, and complex themes, X-Men 2 is a thrilling and thought-provoking sequel that expands the X-Men universe in exhilarating ways. ",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BNjcxMzZhZTEtMmEwYi00NDJmLWE5ZmUtOWJiMzRmMzEzMTY3L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_FMjpg_UX579_.jpg",
    },
    {
        "uid": "The Punisherx",
        "title": "The Punisher",
        "year": 2004,
        "rating": 6.4,
        "description": "The Punisher portrays Frank Castle, a former Marine turned vigilante, as he wages a relentless war on crime after his family's tragic murder. Armed with military skills and a thirst for vengeance, Castle becomes the brutal anti-hero known as the Punisher. Blurring the lines between justice and revenge, he dispenses his own brand of ruthless justice while grappling with his own moral code and haunted past in a gritty and compelling tale of vigilante justice.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BNzE2MTdkYTctM2IxNC00ODA1LWFjZjktMmRjMjQwMDVjNTJhXkEyXkFqcGdeQXVyMzUwNDIxMjQ@._V1_FMjpg_UX426_.jpg",
    },
    {
        "id": "Spider-Man",
        "uid": "Spider-Man2",
        "title": "Spider-Man2",
        "year": 2004,
        "rating": 7.5,
        "description": "Spider-Man 2 delves deeper into the life of Peter Parker as he struggles to balance his responsibilities as a superhero with his personal life. Wrestling with self-doubt and the burden of his secret identity, Peter faces new challenges when his powers begin to falter. Meanwhile, a new villain, Dr. Octopus, emerges, threatening the city. Packed with exhilarating action, heartfelt emotion, and themes of sacrifice and redemption, Spider-Man 2 is a gripping and poignant continuation of the web-slinger's journey.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMzY2ODk4NmUtOTVmNi00ZTdkLTlmOWYtMmE2OWVhNTU2OTVkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1021_.jpg",
    },
    {
        "uid": "Blade: Trinity",
        "title": "Blade: Trinity",
        "year": 2004,
        "rating": 5.8,
        "description": "Blade: Trinity follows the Daywalker, Blade, as he teams up with a group of vampire hunters called the Nightstalkers to take down the ancient vampire Dracula, who poses a threat to both humans and vampires. As they face off against their formidable enemy, Blade confronts his own demons and battles with newfound allies, including the resourceful Abigail and wisecracking Hannibal King. Packed with intense action, supernatural thrills, and dark humor, Blade: Trinity is a thrilling and action-packed conclusion to the Blade trilogy.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMTU2MTAwOTg5N15BMl5BanBnXkFtZTcwOTkzMjkyMQ@@._V1_FMjpg_UX500_.jpg",
    },
    {
        "uid": "Elektra",
        "title": "Elektra",
        "year": 2005,
        "rating": 4.7,
        "description": "Elektra follows the titular character, a skilled assassin, as she seeks redemption and battles her inner demons while protecting a young girl from deadly assassins. With her formidable martial arts abilities and heightened senses, Elektra navigates a world of danger and betrayal, confronting her past and embracing her destiny as a warrior. Packed with intense action, emotional depth, and themes of redemption, Elektra is a gripping tale of strength, resilience, and self-discovery.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BMTI3MTUwNzM5MV5BMl5BanBnXkFtZTcwNzczMDIzMw@@._V1_FMjpg_UY2048_.jpg",
    },
    {
        "uid": "Man-Thing",
        "title": "Man-Thing",
        "year": 2005,
        "rating": 4.1,
        "description": "Man-Thing tells the story of Ted Sallis, a scientist who becomes the monstrous guardian of the Nexus of All Realities after a tragic accident transforms him into the swamp-dwelling creature known as Man-Thing. As dark forces threaten to unleash chaos upon the world, Man-Thing must confront his own inner turmoil and protect the swamp and its inhabitants from destruction. Packed with eerie atmosphere, supernatural thrills, and themes of environmentalism and redemption, Man-Thing is a gripping and atmospheric tale of horror and heroism.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BY2ZkYzNjM2EtY2ExZS00NmYyLTlmNTgtZDdkMmU2Mjg1OTFkL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_FMjpg_UX1000_.jpg",
    },
    {
        "uid": "Fantastic Four(I)",
        "title": "Fantastic Four(I)",
        "year": 2005,
        "rating": 5.7,
        "description": "Fantastic Four chronicles the origin of Marvel's first family of superheroes: scientist Reed Richards, his love interest Sue Storm, her hot-headed brother Johnny, and Reed's best friend Ben Grimm. After a cosmic accident imbues them with extraordinary powers, they must band together to thwart the nefarious plans of their former colleague, Victor Von Doom. Packed with action, adventure, and camaraderie, Fantastic Four is a classic tale of heroes rising to face incredible challenges.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BOGE2ZGVhNjYtZTViYi00NDI5LWEyZjAtMGRmYjczNDVmODc3XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_FMjpg_UX945_.jpg",
    },
    {
        "id": "X-Men",
        "uid": "X-Men: The Last Stand",
        "title": "X-Men: The Last Stand",
        "year": 2006,
        "rating": 6.6,
        "dlink": "https://pub-65d1ce5067144de98830f9f4d1eb1dea.r2.dev/X-Men.3.The.Last.Stand.2006.REMASTERED.1080p.Bluray.Hindi.English.Vegamovies.NL.mkv",
        "description": "X-Men: The Last Stand sees the mutant team facing their greatest challenge yet when a cure for mutation divides them. As tensions rise and old wounds reopen, they must unite to stop Magneto's Brotherhood of Mutants from waging war on humanity and mutantkind alike. Amidst the chaos, a resurrected Jean Grey, now the powerful Phoenix, threatens to destroy everything in her path. Packed with intense action, emotional stakes, and moral dilemmas, it's a gripping conclusion to the original X-Men trilogy.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BNzQ0MmI3MGEtYzVjMi00ZjcyLWFiOTUtYTc3NzllNGViNTI4XkEyXkFqcGdeQXVyOTc5MDI5NjE@._V1_FMjpg_UX1066_.jpg",
    },
    {
        "id": "Ghost Rider",
        "uid": "Ghost Rider",
        "title": "Ghost Rider",
        "year": 2007,
        "rating": 5.3,
        "description": "Ghost Rider follows stuntman Johnny Blaze, who makes a pact with the devil to save his father from cancer, only to be cursed with becoming the Ghost Rider, a fiery spirit of vengeance. As he battles demonic forces and struggles with his cursed fate, Blaze seeks redemption by using his supernatural powers to hunt down evildoers. Packed with supernatural thrills, intense action, and themes of redemption and atonement, Ghost Rider is a dark and thrilling supernatural adventure.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BYThlYTZiZWMtOTE0NC00YTRmLWFhYjAtNjNjNmI1NjNjYWU2XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_FMjpg_UX743_.jpg",
    },
    {
        "id": "Spider-Man3",
        "uid": "Spider-Man3",
        "title": "Spider-Man3",
        "year": 2007,
        "rating": 6.3,
        "dlink": "https://pub-5902af39b28746f883a68387545b3b9a.r2.dev/SpiderMan.3.2007.1080p.Dual.Audio.Hin-Eng.[Vegamovies.NL].mkv",
        "description": "Spider-Man 3 sees Peter Parker grappling with newfound fame as his alter ego, Spider-Man, while facing internal conflicts and external threats. As Peter's life becomes increasingly complicated, including strained relationships with Mary Jane and Harry Osborn, he must confront the vengeful Sandman and the sinister symbiote that amplifies his dark side. Packed with explosive action, emotional depth, and themes of forgiveness and redemption, Spider-Man 3 is a complex and ambitious installment in the beloved superhero franchise that tests the limits of its hero's resolve.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BYTk3MDljOWQtNGI2My00OTEzLTlhYjQtOTQ4ODM2MzUwY2IwXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_FMjpg_UX750_.jpg",
    },
    {
        "uid": "Fantastic Four Rise",
        "title": "Fantastic Four:Rise of the Silver Surfer",
        "year": 2007,
        "rating": 5.6,
        "description": "Fantastic Four: Rise of the Silver Surfer sees the superhero team facing their greatest challenge yet when an enigmatic cosmic entity, the Silver Surfer, heralds the arrival of the planet-devouring entity, Galactus. As they race against time to unravel the Surfer's motives and stop Galactus' destruction, the Fantastic Four must confront personal conflicts and unite to save Earth from annihilation. Packed with thrilling action and cosmic adventure, it's a high-stakes battle for the fate of the world.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BODA4YTc5N2QtNzQyYS00ZDUzLWI3M2UtZWI2OWVhOGZlN2MxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UY1846_.jpg",
    },
    {
        "uid": "Punisher: War Zone",
        "title": "Punisher: War Zone",
        "year": 2008,
        "rating": 5.9,
        "description": "Punisher: War Zone depicts Frank Castle's relentless war on crime, now with a deadlier focus on the criminal underworld led by the sadistic Jigsaw. As Castle wages a one-man crusade, leaving a trail of destruction in his wake, he crosses paths with an FBI agent, a vengeful widow, and a reformed criminal, each with their own agenda. Packed with brutal action, gritty realism, and dark humor, War Zone explores the blurred lines between justice and vengeance, showcasing the Punisher's unyielding pursuit of his own brand of brutal justice in a city consumed by chaos.",
        "thumbnail": "https://m.media-amazon.com/images/M/MV5BYjlmODc5ZjMtOGNhNC00ZDdmLWEzNGYtM2FiOGI5MzIzMWE4XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_FMjpg_UX1012_.jpg",
    },
]